# 1
# from random import choice, shuffle
# from string import digits
# symbols =  digits
# def generate_password(len_: int = 10) -> str:
#     """Function generator random string for password, parametr
#     len needs to give lenghts of password.
#     if blank len_ = 8"""
#     res = [choice(symbols) for _ in range(len_ -2)] + [choice(digits) for _ in range(2)]
#     shuffle(res)
#     return''. join(res)

# print('ID:',generate_password(),'\nФункция запущена ' )

# 2
# def ls(ass): 
#     ass_dict= ass.split()
#     for x in range(len(ass_dict)): 
#        print(ass_dict[x][0].upper(), end = "") 
 
# ls('Кыргыз Республик ')


















